<script setup lang="ts">
import {ref,computed,watch,onBeforeUnmount,nextTick} from 'vue';
import {Plus,FolderOpen,X,LoaderCircle,ChevronDown,ClipboardPaste,RefreshCw} from '@lucide/vue';
import {audioFor,orderedVideos,canMp4,hasAudio,codecLabel,sizeLabel,groupFormats,audioLabel,audioIdentity,languageLabel} from '../formats';
import type {Metadata,Settings} from '../types';
import {settings,command,showError,addTasks,parseLinks,desktop,notify,chooseDirectory,saveSettings} from '../store';
const url=ref(''),batch=ref(false),links=ref(''),probing=ref(false),adding=ref(false),advanced=ref(false),probeError=ref('');const metadata=ref<Metadata|null>(null);const video=ref(''),audio=ref('');const quality=ref<number|null>(settings.quality_height),mode=ref(settings.output_mode);let generation=0,timer:ReturnType<typeof setTimeout>|undefined;let disposed=false;
watch(()=>settings.quality_height,v=>quality.value=v);watch(()=>settings.output_mode,v=>mode.value=v);
const parsed=computed(()=>parseLinks(links.value));
const videos=computed(()=>orderedVideos(metadata.value?.formats||[]));
const audios=computed(()=>(metadata.value?.formats||[]).filter(f=>hasAudio(f)&&(!f.vcodec||f.vcodec==='none')).sort((a,b)=>(b.abr||0)-(a.abr||0)));
const videoGroups=computed(()=>groupFormats(videos.value,'video'));
const audioLanguage=ref('');
const audioLanguages=computed(()=>[...new Set(audios.value.map(f=>f.language||''))]);
const audioGroups=computed(()=>groupFormats(audios.value.filter(f=>!audioLanguage.value||(f.language||'unknown')===audioLanguage.value),'audio'));
function changeAudioLanguage(){audio.value=audioFor(audios.value.filter(f=>(f.language||'unknown')===audioLanguage.value),selected.value)?.format_id||''}
const selected=computed(()=>videos.value.find(f=>f.format_id===video.value)||videos.value.find(f=>quality.value===null||(f.height||0)<=quality.value));
const combined=computed(()=>hasAudio(selected.value));
const selectedAudio=computed(()=>combined.value?selected.value:audios.value.find(f=>f.format_id===audio.value)||audioFor(audios.value.filter(f=>!audioLanguage.value||(f.language||'unknown')===audioLanguage.value),selected.value));
const formatsLabel=computed(()=>{
  if(!metadata.value)return '';
  if(mode.value==='subtitles')return '仅下载字幕 · UTF-8 SRT · 不下载视频';
  if(mode.value==='audio')return '容器：MP3 · 提取并转换音频，不保存视频';
  const v=selected.value;if(!v)return '未找到目标清晰度的视频流；下载时重新检查';
  const ac=selectedAudio.value?.acodec;
  const container=canMp4(v,selectedAudio.value)?'MP4':'MKV';
  const source=`${v.height||'未知'}p · ${codecLabel(v.vcodec)}${selectedAudio.value?' + '+(ac?codecLabel(ac):'音频（编码未知）'):'（无音轨）'}${selectedAudio.value&&audioIdentity(selectedAudio.value)?' · '+audioIdentity(selectedAudio.value):''} · ${container}`;
  return mode.value==='compatible'?`${source} → H.264 MP4 · 自动转码`:`${source} · 不转码`;
});
function selectAuto(){video.value=videos.value.find(f=>quality.value===null||(f.height||0)<=quality.value)?.format_id||'';selectAudio()}
function selectAudio(){const f=audioFor(metadata.value?.formats||[],selected.value);audio.value=f?.format_id||'';audioLanguage.value=f?.language||'unknown'}
watch(video,selectAudio);watch(quality,selectAuto);
async function analyze(){const value=url.value.trim();const id=++generation;probeError.value='';metadata.value=null;if(!parseLinks(value).valid.length||value.includes('\n')){probing.value=false;return}probing.value=true;try{const data=await command<Metadata>('probe_video',{request:{url:value,proxy:settings.use_proxy?settings.proxy:null,cookies_browser:settings.cookies_browser||null,cookies_file:null}});if(id!==generation||disposed)return;metadata.value=data;selectAuto()}catch(e){if(id===generation&&!disposed)probeError.value=String(e)}finally{if(id===generation&&!disposed)probing.value=false}}
watch(url,()=>{generation++;clearTimeout(timer);metadata.value=null;probeError.value='';probing.value=false;if(desktop&&url.value.trim())timer=setTimeout(analyze,450)});
watch(()=>[settings.proxy,settings.use_proxy,settings.cookies_browser],()=>{if(url.value)void analyze()});
onBeforeUnmount(()=>{disposed=true;generation++;clearTimeout(timer)});
async function paste(){try{const value=await command<string>('read_clipboard_text');if(value.includes('\n')){links.value=value;batch.value=true}else url.value=value.trim()}catch(e){showError(e)}}
function pasted(e:ClipboardEvent){const text=e.clipboardData?.getData('text')||'';if(text.includes('\n')){e.preventDefault();links.value=text;batch.value=true}}
async function add(start:boolean,multi=false){adding.value=true;try{const sources=multi?parsed.value.valid:[url.value.trim()];if(!sources.length||(!multi&&!parseLinks(url.value).valid.length))throw new Error('请输入有效的视频链接');await addTasks(sources,'download',start,multi?null:metadata.value,multi?null:video.value||null,multi?null:selectedAudio.value?.format_id||null,{quality_height:quality.value,output_mode:mode.value} as Partial<Settings>);if(multi){batch.value=false;links.value=''}else{url.value='';metadata.value=null}notify(start?'已加入下载队列':'已加入等待队列','download')}catch(e){showError(e)}finally{adding.value=false}}
async function importTxt(){try{const value=await command<string|null>('import_links');if(value!==null)links.value=value}catch(e){showError(e)}}
async function showBatch(){batch.value=true;await nextTick();document.querySelector<HTMLTextAreaElement>('#batch-links')?.focus()}
</script>
<template><section class="composer"><div class="entry"><input v-model="url" aria-label="视频链接" placeholder="粘贴视频链接，自动解析清晰度与编码" @paste="pasted" @keyup.enter="!probing&&analyze()"><button class="icon-button" aria-label="粘贴链接" @click="paste"><ClipboardPaste :size="18"/></button><button class="button primary" :disabled="adding||probing||!url.trim()" @click="add(true)"><LoaderCircle v-if="probing||adding" :size="16" class="spin"/><Plus v-else :size="16"/>{{probing?'解析中':'下载'}}</button><button class="button" @click="showBatch">批量添加</button></div>
<div class="download-options"><button class="button quiet path" @click="chooseDirectory().catch(showError)" :title="settings.output_dir"><FolderOpen :size="15"/>{{settings.output_dir||'选择保存目录'}}</button><select v-if="mode!=='subtitles'" v-model="quality" aria-label="清晰度"><option :value="null">最高可用</option><option :value="2160">不超过 2160p</option><option :value="1080">不超过 1080p</option><option :value="720">不超过 720p</option></select><select v-model="mode" aria-label="输出方式"><option value="original">保留原始画质</option><option value="compatible">自动转码 · H.264 MP4</option><option value="audio">仅音频 · MP3</option><option value="subtitles">仅字幕 · SRT</option></select><button v-if="mode!=='subtitles'" class="button quiet" @click="advanced=!advanced" :aria-expanded="advanced">高级设置<ChevronDown :size="14"/></button></div>
<div class="subtitle-options">
<label v-if="mode!=='subtitles'" class="filename-option"><input type="checkbox" v-model="settings.subtitles.enabled" @change="saveSettings().catch(showError)"><span>同时下载字幕 · SRT</span></label>
<span v-else class="fine">仅下载字幕 · SRT</span>
<template v-if="settings.subtitles.enabled||mode==='subtitles'">
<div class="fields"><label>字幕语言<select aria-label="字幕语言" v-model="settings.subtitles.language" @change="saveSettings().catch(showError)"><option value="en">英文</option><option value="zh">中文（优先简体）</option><option value="bilingual">中英双语</option></select></label>
<label>字幕来源<select aria-label="字幕来源" v-model="settings.subtitles.source" @change="saveSettings().catch(showError)"><option value="prefer">优先原生，缺失时自动字幕</option><option value="manual">仅原生字幕</option><option value="auto">仅自动生成 / 翻译字幕</option></select></label></div>
<p class="fine">与视频保存在同一目录。双语模式另存中文、英文和双语 SRT，中文在上、英文在下。自动翻译取决于网站是否提供，缺少所选字幕会提示。</p>
</template></div>
<div class="probe-preview" v-if="metadata||probing"><div class="thumbnail large"><img v-if="metadata?.thumbnail" :src="metadata.thumbnail" alt="视频封面"><LoaderCircle v-else-if="probing" class="spin" :size="24"/></div><div><strong>{{metadata?.title||'正在读取视频信息…'}}</strong><p>{{metadata?[metadata.extractor,metadata.duration_string||'时长未知'].join(' · '):'读取标题、清晰度、视频编码和音频编码'}}</p><span v-if="metadata" class="success-text">解析完成，等待开始下载</span></div><button v-if="metadata" class="button quiet" @click="add(false)" :disabled="adding">仅加入队列</button></div>
<div class="output-plan" v-if="metadata">{{formatsLabel}}</div><div class="alert error" v-if="probeError"><span class="break">{{probeError}}</span><button class="button" @click="analyze"><RefreshCw :size="15"/>重新解析</button></div>
<div class="advanced-panel" v-if="advanced&&mode!=='subtitles'"><div v-if="audioLanguages.length>1" class="audio-language"><label>音轨语言 <select v-model="audioLanguage" @change="changeAudioLanguage"><option v-for="lang in audioLanguages" :key="lang" :value="lang||'unknown'">{{lang?languageLabel(lang):'语言未标注'}}{{audios.some(f=>f.language===lang&&(f.language_preference||0)>=10)?' · 原声':''}}</option></select></label><span class="muted">优先选择原声，可切换其他语言</span></div><div class="fields"><label>视频流<select v-model="video" :disabled="mode==='audio'||!videos.length"><option value="">自动选择</option><optgroup v-for="group in videoGroups" :key="group.codec" :label="group.codec"><option v-for="f in group.formats" :key="f.format_id" :value="f.format_id">{{f.height||'未知'}}p · {{codecLabel(f.vcodec)}} · {{f.fps||'未知'}} fps · {{sizeLabel(f)}}{{f.acodec&&f.acodec!=='none'?'（含音轨）':''}}</option></optgroup></select></label><label>音频流<select v-model="audio" :disabled="combined||!audios.length"><option value="">{{combined?'使用视频内置音轨':'自动选择'}}</option><optgroup v-for="group in audioGroups" :key="group.codec" :label="group.codec"><option v-for="f in group.formats" :key="f.format_id" :value="f.format_id">{{audioLabel(f)}}</option></optgroup></select></label></div><div class="filename-options"><label class="filename-option"><input type="checkbox" v-model="settings.filename_suffix" @change="saveSettings().catch(showError)"><span>文件名添加分辨率</span></label><label class="filename-option" :class="{muted:!settings.filename_suffix}"><input type="checkbox" v-model="settings.filename_codecs" :disabled="!settings.filename_suffix" @change="saveSettings().catch(showError)"><span>同时添加编码</span></label><span class="filename-example">例如：{{settings.filename_codecs&&settings.filename_suffix?'2160p_AV1_AAC':'2160p'}}</span></div></div></section>
<div class="modal-backdrop" v-if="batch" @click.self="batch=false"><section class="modal" role="dialog" aria-modal="true" aria-label="批量添加链接"><header><h2>批量添加链接</h2><button class="icon-button" aria-label="关闭" @click="batch=false"><X :size="20"/></button></header><p class="muted">每行一个视频链接；可混合不同网站。</p><textarea id="batch-links" v-model="links" aria-label="批量视频链接" placeholder="https://www.youtube.com/watch?v=…&#10;https://www.bilibili.com/video/…"/><div class="inline spread"><button class="button" @click="importTxt">导入 TXT</button><span class="fine">有效 {{parsed.valid.length}} · 重复 {{parsed.duplicates}} · 无效 {{parsed.invalid.length}}</span></div><details v-if="parsed.invalid.length"><summary>查看无效链接</summary><pre>{{parsed.invalid.join('\n')}}</pre></details><div class="output-plan">沿用当前设置 · {{quality?`不超过 ${quality}p`:'最高可用'}} · {{mode==='subtitles'?'仅字幕 SRT':mode==='original'?'保留原始画质':mode==='audio'?'仅音频':'H.264 MP4'}}</div><footer class="modal-actions"><button class="button" :disabled="adding||!parsed.valid.length" @click="add(false,true)">仅加入队列</button><button class="button primary" :disabled="adding||!parsed.valid.length" @click="add(true,true)">添加并开始</button></footer></section></div>
</template>
