<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount,watch} from 'vue';
import {Download,Film,Braces,RefreshCw} from '@lucide/vue';
import {settings,saveSettings,chooseDirectory,command,showError,toolsMessage,desktop,notify} from '../store';
import BrowserAuthorization from './BrowserAuthorization.vue';
import type {Environment} from '../types';
const tab=ref('tools'),environment=ref<Environment|null>(null),working=ref(false);const updates=ref<Array<{name:string;version:string;current:string;available:boolean;updated:boolean}>>([]);const login=ref(false),qr=ref(''),loginText=ref('未登录');let qrKey='',poll:ReturnType<typeof setTimeout>|undefined,loginGeneration=0;let disposed=false;
async function check(){try{environment.value=await command<Environment>('check_environment')}catch(e){showError(e)}}
async function tools(action:string,only='all'){working.value=true;try{toolsMessage.value=action==='update'?'正在下载并校验工具，请稍候…':'正在检查工具…';const result=await command<unknown>('manage_tools',{action,only});if(Array.isArray(result))updates.value=result;toolsMessage.value=action==='rollback'?'已恢复上一可用版本':action==='update'?'更新完成，已验证组件可启动':'检查完成';await check()}catch(e){toolsMessage.value=String(e);showError(e)}finally{working.value=false}}
async function save(){try{await saveSettings()}catch(e){showError(e)}}
async function qrLogin(){const generation=++loginGeneration;clearTimeout(poll);qr.value='';try{loginText.value='正在生成二维码';const result=await command<{url:string;qrcode_key:string}>('start_bilibili_qr_login');if(generation!==loginGeneration||disposed)return;qrKey=result.qrcode_key;const QRCode=await import('qrcode');qr.value=await QRCode.toDataURL(result.url,{width:196,margin:1});loginText.value='使用 Bilibili APP 扫码';const tick=async()=>{try{const r=await command<{status:string;message:string;logged_in:boolean}>('poll_bilibili_qr_login',{qrcodeKey:qrKey});if(generation!==loginGeneration||disposed)return;loginText.value=r.message;if(r.logged_in){login.value=true;qr.value='';notify('登录成功，可重新解析视频','settings')}else if(!['expired','error'].includes(r.status))poll=setTimeout(tick,2000)}catch(e){if(generation===loginGeneration)loginText.value=String(e)}};poll=setTimeout(tick,1500)}catch(e){loginText.value=String(e)}}
async function clearLogin(){loginGeneration++;clearTimeout(poll);try{await command('clear_bilibili_login');login.value=false;qr.value='';loginText.value='未登录'}catch(e){showError(e)}}
watch(toolsMessage,()=>{if(toolsMessage.value.includes('自动更新检查完成'))void check()});
onMounted(()=>{if(desktop){void check();void command<{logged_in:boolean}>('get_bilibili_login_status').then(r=>{login.value=r.logged_in;loginText.value=r.logged_in?'已保存登录信息':'未登录'}).catch(showError)}});onBeforeUnmount(()=>{disposed=true;loginGeneration++;clearTimeout(poll)});
defineExpose({tab});
</script>
<template><div class="tabs settings-tabs"><button v-for="t in [{id:'general',name:'常规'},{id:'network',name:'网络与账号'},{id:'encoding',name:'转码'},{id:'tools',name:'工具与更新'}]" :key="t.id" :class="{active:tab===t.id}" @click="tab=t.id">{{t.name}}</button></div>
<section v-if="tab==='tools'"><div class="output-plan">保持下载组件更新，及时获得网站兼容性修复。</div><div class="setting"><div><strong>自动检查并更新工具</strong><p>启动时检查，空闲时更新；正在运行的任务不受影响。</p></div><input type="checkbox" v-model="settings.auto_update" @change="save" aria-label="自动更新工具"></div><div v-for="tool in [{id:'yt-dlp',key:'yt_dlp',name:'yt-dlp',icon:Download,source:'yt-dlp 官方 GitHub · 内含 EJS 挑战脚本'},{id:'ffmpeg',key:'ffmpeg',name:'FFmpeg / FFprobe',icon:Film,source:'FFmpeg 官网列出的 Gyan Windows 构建'},{id:'deno',key:'deno',name:'YouTube 运行依赖 · Deno',icon:Braces,source:'Deno 官方 GitHub · JavaScript 运行时'}]" :key="tool.id" class="tool-row"><div class="tool-icon"><component :is="tool.icon" :size="20"/></div><div><strong>{{tool.name}}</strong><p class="break">{{environment?.[tool.key as keyof Environment]?.version||'待检测'}}</p><p>{{tool.source}}</p><p class="error-text" v-if="environment?.[tool.key as keyof Environment]?.message">{{environment?.[tool.key as keyof Environment]?.message}}</p><p v-if="updates.find(u=>u.name===tool.id)">发布版本：{{updates.find(u=>u.name===tool.id)?.version}}</p></div><button class="button" :disabled="working" @click="tools('update',tool.id)">更新</button></div><div class="setting"><div><strong>更新失败时保留可用版本</strong><p>校验下载、验证启动后切换，可恢复上一次更新前的版本。</p></div><button class="button quiet" :disabled="working" @click="tools('rollback')">恢复上一版本</button></div><div class="inline"><button class="button" :disabled="working" @click="tools('check')"><RefreshCw :size="15" :class="{spin:working}"/>检查更新</button><button class="button primary" :disabled="working" @click="tools('update')">更新全部</button><button class="button quiet" :disabled="working" @click="check">检查环境</button></div><p class="tool-message break" role="status">{{toolsMessage}}</p><p class="fine">软件版本 0.4.0 · 工具版本独立更新 · FFprobe {{environment?.ffprobe.available?'可用':'待检测'}}</p></section>
<section v-else-if="tab==='general'"><div class="setting"><div><strong>默认保存目录</strong><p class="break">{{settings.output_dir||'尚未选择'}}</p></div><button class="button" @click="chooseDirectory().catch(showError)">选择目录</button></div><div class="setting"><strong>同时下载数量</strong><select v-model.number="settings.concurrency" @change="save" aria-label="同时下载数量"><option v-for="n in [1,2,3,4]" :value="n">{{n}} 项</option></select></div><div class="setting"><strong>默认清晰度</strong><select v-model="settings.quality_height" @change="save" aria-label="默认清晰度"><option :value="null">最高可用</option><option :value="1080">不超过 1080p</option><option :value="720">不超过 720p</option></select></div><div class="setting"><strong>默认输出方式</strong><select v-model="settings.output_mode" @change="save" aria-label="默认输出方式"><option value="original">保留原始画质</option><option value="compatible">自动转码 · H.264 MP4</option><option value="audio">仅音频</option></select></div><div class="setting"><div><strong>队列与历史自动保存</strong><p>重启后，中断任务标记为“待恢复”，由你选择继续。</p></div><span class="success-text">已启用</span></div></section>
<section v-else-if="tab==='network'"><div class="setting"><strong>使用代理</strong><input type="checkbox" v-model="settings.use_proxy" @change="save" aria-label="使用代理"></div><div class="inline"><input class="grow" v-model="settings.proxy" aria-label="代理地址" :disabled="!settings.use_proxy"><button class="button" @click="save">保存</button></div><BrowserAuthorization/><div class="setting"><div><strong>直接读取浏览器（备用）</strong><p>可能受数据库占用或加密限制；已保存的网站授权优先使用</p></div><select v-model="settings.cookies_browser" @change="save" aria-label="浏览器登录状态"><option value="">不使用</option><option value="edge">Microsoft Edge</option><option value="chrome">Chrome</option><option value="firefox">Firefox</option></select></div><div class="setting"><div><strong>Bilibili 账号</strong><p>{{loginText}}</p></div><div class="inline"><button class="button" @click="qrLogin">{{login?'重新扫码':'扫码登录'}}</button><button class="button quiet" :disabled="!login&&!qr" @click="clearLogin">清除登录</button></div></div><img v-if="qr" :src="qr" class="qr" alt="Bilibili 登录二维码"><p class="fine">可用清晰度取决于视频和账号权限。已加入队列的任务保留其设置。</p></section>
<section v-else><div class="output-plan">在转码页面选择编码、画质、音频及输出设置，点击“保存为默认设置”。本地转码设置不会改变下载页面的“自动转码 · H.264 MP4”。</div><div class="setting"><div><strong>保留源文件</strong><p>关闭后，仅在输出验证成功时删除源文件。</p></div><input type="checkbox" v-model="settings.keep_source" @change="save" aria-label="保留源文件"></div><div class="setting"><strong>同时转码数量</strong><span>1 项</span></div><p class="fine">输出使用独立文件名，同名文件自动避让。</p></section>
</template>
