<script setup lang="ts">
import {computed,ref,watch} from 'vue';
import {FolderOpen,FileVideo,X,Pause,Play,Check, CircleAlert} from '@lucide/vue';
import {snapshot,action,label,openFolder,command,showError,notify} from '../store';
import {codecLabel} from '../formats';
import type {Task} from '../types';
const props=defineProps<{kind:string}>();
const filter=ref('all'),detailId=ref<string|null>(null),conflictId=ref<string|null>(null),removeId=ref<string|null>(null);
const clearing=ref(false),busy=ref(false);
const selected=computed(()=>snapshot.tasks.find(t=>t.id===detailId.value));
const conflict=computed(()=>snapshot.tasks.find(t=>t.id===conflictId.value&&t.status==='awaiting_name'));
const tasks=computed(()=>snapshot.tasks.filter(t=>t.kind===props.kind));
const filtered=computed(()=>tasks.value.filter(t=>filter.value==='all'||(filter.value==='active'?['running','pausing','paused','queued','waiting','interrupted','awaiting_name'].includes(t.status):t.status===filter.value)).slice().reverse());
const completed=computed(()=>tasks.value.filter(t=>t.status==='done').length);
const failed=computed(()=>tasks.value.filter(t=>t.status==='error').length);
const clearable=computed(()=>tasks.value.filter(t=>['done','error','cancelled'].includes(t.status)).length);
const dispatchWork=computed(()=>snapshot.tasks.some(t=>['running','pausing','paused','queued'].includes(t.status)));
const pendingConflict=computed(()=>tasks.value.find(t=>t.status==='awaiting_name')?.id);
watch(pendingConflict,id=>{if(id)conflictId.value=id},{immediate:true});
function meta(t:Task){
 if(t.kind==='transcode'){const o=t.settings.transcode;return o?`${o.codec==='h265'?'H.265':'H.264'} · ${o.mode==='size'?`${o.target_mb} MB`:`CRF ${o.codec==='h265'?o.crf_h265:o.crf_h264}`} · ${(t.output?.container||o.container).toUpperCase()}`:'本地转码'}
 const f=t.metadata?.formats.find(f=>f.format_id===t.video_format_id);
 return [t.metadata?.extractor,t.output?.container.toUpperCase()||({original:'原始画质',compatible:'H.264 MP4',audio:'MP3'} as Record<string,string>)[t.settings.output_mode],t.settings.output_mode==='audio'?'':f?.height?`${f.height}p`:t.settings.quality_height?`不超过 ${t.settings.quality_height}p`:'自动画质',t.output?.selected_vcodec?codecLabel(t.output.selected_vcodec):f?codecLabel(f.vcodec):''].filter(Boolean).join(' · ')
}
async function retryAll(){for(const t of tasks.value.filter(t=>t.status==='error'))await action(t.id,'retry')}
async function clearList(){try{const count=await command<number>('clear_tasks',{kind:props.kind});notify(`已清除 ${count} 条记录，文件已保留`,props.kind);clearing.value=false}catch(e){showError(e)}}
async function resolveName(choice:string){if(!conflict.value||busy.value)return;busy.value=true;try{await command('task_action',{id:conflict.value.id,action:choice});conflictId.value=null}catch(e){showError(e)}finally{busy.value=false}}
function remove(t:Task){if(['running','pausing'].includes(t.status))removeId.value=t.id;else void action(t.id,'remove')}
async function cancelAndRemove(){if(!removeId.value)return;busy.value=true;const id=removeId.value;try{
 await command('task_action',{id,action:'cancel'});
 for(let i=0;i<100;i++){if(!['running','pausing'].includes(snapshot.tasks.find(t=>t.id===id)?.status||'')){await command('task_action',{id,action:'remove'});removeId.value=null;return}await new Promise(r=>setTimeout(r,100))}
 throw new Error('正在停止任务，请稍后再次移除。');
}catch(e){showError(e)}finally{busy.value=false}}
</script>
<template>
<div class="queue-toolbar"><div class="tabs"><button v-for="f in [{id:'all',name:'全部'},{id:'active',name:'进行中'},{id:'done',name:'已完成'},{id:'error',name:'失败'}]" :key="f.id" :class="{active:filter===f.id}" @click="filter=f.id">{{f.name}} <span v-if="f.id==='all'">{{tasks.length}}</span></button></div><div class="inline queue-buttons"><button class="button quiet" :disabled="!clearable" @click="clearing=true">清除列表</button><button class="button quiet" :disabled="!failed" @click="retryAll">重试失败</button><button class="button" :disabled="!dispatchWork" :title="dispatchWork?(snapshot.paused?'继续下载；未完成的转码将重新开始':'停止当前下载并保留片段，同时暂停后续任务；未完成的转码继续时重新开始'):'暂无正在运行或排队的任务'" @click="action('',snapshot.paused?'resume':'pause')"><Play v-if="snapshot.paused" :size="15"/><Pause v-else :size="15"/>{{snapshot.paused&&dispatchWork?'继续队列':'暂停队列'}}</button><button class="button primary" v-if="tasks.some(t=>['waiting','interrupted'].includes(t.status))" @click="action('','resume')"><Play :size="15"/>开始等待任务</button></div></div>
<div class="task-list"><div v-if="!filtered.length" class="empty"><FileVideo :size="28"/><strong>{{tasks.length?'没有符合条件的任务':'还没有任务'}}</strong><span>{{kind==='download'?'粘贴视频链接，或批量添加多个链接。':'添加本地视频，选择编码与压制方式。'}}</span></div>
<article v-for="task in filtered" :key="task.id" :class="['task-row',{'task-waiting':['waiting','queued','paused','pausing','interrupted','awaiting_name'].includes(task.status)}]"><div class="thumbnail"><img v-if="task.metadata?.thumbnail" :src="task.metadata.thumbnail" alt="" loading="lazy" @error="($event.target as HTMLImageElement).style.display='none'"><FileVideo v-else :size="23"/></div><div class="task-copy"><strong :title="task.title">{{task.title}}</strong><span>{{meta(task)}}</span></div><div class="task-progress"><div :class="['stage',task.status]"><span class="status-label" :class="{'clickable-status':task.status==='error'}" @click="task.status==='error'&&(detailId=task.id)"><Pause v-if="task.status==='paused'" :size="15"/><Check v-if="task.status==='done'" :size="15"/><CircleAlert v-if="task.status==='error'" :size="15"/>{{label(task)}}</span><span v-if="['running','pausing','paused'].includes(task.status)">{{Math.round(task.percent)}}%</span></div><progress v-if="['running','pausing','paused'].includes(task.status)" :value="task.percent" max="100" :aria-label="task.stage"/><small v-if="task.status==='running'">{{[task.speed,task.eta?`剩余 ${task.eta}`:''].filter(Boolean).join(' · ')}}</small><button v-if="task.status==='error'" class="failure-reason" @click="detailId=task.id">点击查看原因</button></div><div class="row-actions"><button v-if="task.status==='awaiting_name'" class="button quiet" @click="conflictId=task.id">选择文件名</button><button v-else class="button quiet" @click="detailId=task.id">详情</button><button v-if="['error','cancelled','interrupted'].includes(task.status)" class="button quiet" @click="action(task.id,'retry')">{{task.downloaded?'重试转码':'重试'}}</button><button v-if="task.status==='done'&&task.output" class="icon-button" aria-label="打开文件夹" @click="openFolder(task.output!.output_path)"><FolderOpen :size="16"/></button><button class="icon-button remove-task" :aria-label="`移除任务：${task.title}`" title="移除记录，保留文件" @click="remove(task)"><X :size="16"/></button></div></article></div>
<footer class="queue-footer"><span>已完成 {{completed}} / {{tasks.length}}<template v-if="failed"> · {{failed}} 项失败</template></span><span>同时下载 {{snapshot.settings.concurrency}} 项 / 转码 1 项</span></footer>
<div class="modal-backdrop" v-if="selected" @click.self="detailId=null"><section class="modal detail" role="dialog" aria-modal="true" aria-label="任务详情"><header><h2>任务详情</h2><button class="icon-button" aria-label="关闭" @click="detailId=null"><X :size="20"/></button></header><h3>{{selected.title}}</h3><p class="muted break">{{selected.source}}</p><dl><dt>状态</dt><dd>{{label(selected)}}</dd><dt>创建时间</dt><dd>{{new Date(selected.created*1000).toLocaleString()}}</dd><dt>源文件</dt><dd>{{selected.settings.keep_source?'保留':'成功转码后删除'}}</dd><dt>保存目录</dt><dd class="break">{{selected.kind==='transcode'?(selected.settings.batch_output_dir||'原文件所在目录'):selected.settings.output_dir}}</dd><dt v-if="selected.output">输出文件</dt><dd v-if="selected.output" class="break">{{selected.output.output_path}}</dd></dl><div v-if="selected.error" class="alert error break">{{selected.error}}</div><details v-if="selected.output||selected.downloaded"><summary>查看处理日志</summary><pre>{{selected.output?.log||selected.downloaded?.log}}</pre></details><footer class="modal-actions"><button v-if="selected.output||selected.downloaded" class="button" @click="openFolder((selected.output||selected.downloaded)!.output_path)">打开文件夹</button><button v-if="['running','pausing','paused','queued','waiting'].includes(selected.status)" class="button" @click="action(selected.id,'cancel')">取消任务</button><button v-else class="button" @click="action(selected.id,'remove');detailId=null">移除记录</button><button class="button primary" v-if="['error','cancelled','interrupted'].includes(selected.status)" @click="action(selected.id,'retry');detailId=null">{{selected.downloaded?'仅重试转码':'重试任务'}}</button></footer><p class="fine">移除记录不会删除已下载文件。</p></section></div>
<div v-if="conflict?.name_conflict" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="文件名重复"><h2>已有同名视频</h2><p class="muted">原文件会保留。是否为这次下载添加分辨率后缀（按设置附带编码）？</p><p class="fine break">已有文件：{{conflict.name_conflict.existing}}</p><div class="output-plan break">建议名称：{{conflict.name_conflict.suggested.split(/[\\/]/).pop()}}</div><footer class="modal-actions"><button class="button quiet" :disabled="busy" @click="resolveName('cancel')">取消下载</button><button class="button" :disabled="busy" @click="resolveName('name_number')">不加后缀，自动编号</button><button class="button primary" :disabled="busy" @click="resolveName('name_suffix')">添加后缀并继续</button></footer></section></div>
<div v-if="clearing" class="modal-backdrop" @click.self="clearing=false"><section class="modal" role="dialog" aria-modal="true" aria-label="清除列表"><h2>清除已结束的任务记录？</h2><p>将清除 {{clearable}} 条已完成、失败或取消的记录。保留下载文件及尚未结束的任务。</p><footer class="modal-actions"><button class="button" @click="clearing=false">返回</button><button class="button primary" @click="clearList">清除记录</button></footer></section></div>
<div v-if="removeId" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="取消并移除任务"><h2>取消并移除正在运行的任务？</h2><p>已下载的文件不会删除。</p><footer class="modal-actions"><button class="button" :disabled="busy" @click="removeId=null">返回</button><button class="button primary" :disabled="busy" @click="cancelAndRemove">取消并移除</button></footer></section></div>
</template>
