<script setup lang="ts">
import {ref,computed,watch,onBeforeUnmount} from 'vue';
import {Files,Plus,X,LoaderCircle} from '@lucide/vue';
import {settings,command,showError,addTasks,notify,chooseDirectory,saveSettings} from '../store';
import {codecLabel} from '../formats';
import type {LocalMedia,TranscodePlan} from '../transcode';
type Entry={path:string;media?:LocalMedia;plan?:TranscodePlan;error:string};
const files=ref<Entry[]>([]),busy=ref(false),preparing=ref(false),customDir=ref(false),sizeUnit=ref('MB');let generation=0,timer:ReturnType<typeof setTimeout>|undefined,disposed=false;
const o=computed(()=>settings.transcode);
const customAudio=ref(![0,96,128,160,192,256,320].includes(o.value.audio_kbps));
const audioRate=computed({get:()=>customAudio.value?'custom':String(o.value.audio_kbps),set:(v:string)=>{customAudio.value=v==='custom';if(!customAudio.value)o.value.audio_kbps=Number(v);else if(o.value.audio_kbps===0)o.value.audio_kbps=192}});
const crf=computed({get:()=>o.value.codec==='h264'?o.value.crf_h264:o.value.crf_h265,set:v=>{if(o.value.codec==='h264')o.value.crf_h264=v;else o.value.crf_h265=v}});
const preset=computed({get:()=>o.value.codec==='h264'?o.value.preset_h264:o.value.preset_h265,set:v=>{if(o.value.codec==='h264')o.value.preset_h264=v;else o.value.preset_h265=v}});
const targetSize=computed({get:()=>o.value.target_mb/(sizeUnit.value==='GB'?1000:1),set:v=>o.value.target_mb=v*(sizeUnit.value==='GB'?1000:1)});
const first=computed(()=>files.value.find(f=>f.media)?.media);
const ready=computed(()=>files.value.length>0&&!busy.value&&!preparing.value&&files.value.every(f=>f.plan&&!f.error));
const summary=computed(()=>`${o.value.codec==='h264'?'H.264':'H.265'} · ${o.value.mode==='crf'?`CRF ${crf.value}`:`每个文件 ${o.value.target_mb} MB · 两遍编码`} · ${preset.value} · ${o.value.audio==='none'?'无音频':o.value.audio==='copy'?'复制音频':`AAC ${o.value.audio_kbps?o.value.audio_kbps+' kbps':'参考源码率'}`} · ${o.value.container.toUpperCase()}`);
function bytes(n:number){return `${(n/1e6).toFixed(1)} MB`}
function duration(n:number){return `${Math.floor(n/60)}:${Math.floor(n%60).toString().padStart(2,'0')}`}
function dimensions(anchor:string){o.value.anchor=anchor;const m=first.value;if(o.value.lock_ratio&&m){if(anchor==='width')o.value.height=Math.max(2,Math.round(o.value.width*m.height/m.width/2)*2);else o.value.width=Math.max(2,Math.round(o.value.height*m.width/m.height/2)*2)}}
async function refresh(){const id=++generation;clearTimeout(timer);if(!files.value.length){preparing.value=false;return}preparing.value=true;const options=JSON.parse(JSON.stringify(o.value));const batch=[...files.value];
 for(const file of batch){if(id!==generation||disposed)return;try{const plan=await command<TranscodePlan>('inspect_transcode',{path:file.path,options});if(id!==generation||disposed)return;file.plan=plan;file.media=plan.media;file.error=''}catch(e){if(id!==generation||disposed)return;file.plan=undefined;file.error=String(e)}}
 if(id===generation)preparing.value=false;
}
watch(o,()=>{generation++;preparing.value=files.value.length>0;clearTimeout(timer);timer=setTimeout(refresh,550)},{deep:true});
async function addPaths(paths:string[]){const existing=new Set(files.value.map(f=>f.path.toLowerCase()));const added:Entry[]=[];for(const path of paths){if(!existing.has(path.toLowerCase())){existing.add(path.toLowerCase());added.push({path,error:''})}}files.value.push(...added);if(!added.length)return;
 generation++;preparing.value=true;for(const file of files.value.filter(f=>!f.media)){try{file.media=await command<LocalMedia>('inspect_media',{path:file.path})}catch(e){file.error=String(e)}}if(disposed)return;await refresh();
}
async function chooseFiles(){try{await addPaths(await command<string[]>('select_video_files'))}catch(e){showError(e)}}
function clear(){generation++;clearTimeout(timer);files.value=[];preparing.value=false}
function remove(path:string){files.value=files.value.filter(f=>f.path!==path);void refresh()}
async function start(){if(!ready.value)return;busy.value=true;try{if(customDir.value&&!settings.batch_output_dir)throw Error('请选择输出目录');await addTasks(files.value.map(f=>f.path),'transcode',true,null,null,null,{transcode:JSON.parse(JSON.stringify(o.value)),batch_output_dir:customDir.value?settings.batch_output_dir:''});clear();notify('已加入转码队列，本批任务设置已固定','transcode')}catch(e){showError(e)}finally{busy.value=false}}
onBeforeUnmount(()=>{disposed=true;generation++;clearTimeout(timer)});defineExpose({chooseFiles,addPaths});
</script>
<template><section class="transcode-input">
<button v-if="!files.length" class="drop-zone" @click="chooseFiles"><Files :size="27"/><strong>拖入本地视频，或点击添加</strong><span>支持继续添加多个文件，逐个检测输出设置</span></button>
<template v-else><header class="input-toolbar"><strong>待转码文件 · {{files.length}}</strong><div class="inline"><button class="button quiet" @click="clear" :disabled="busy">清空列表</button><button class="button" @click="chooseFiles" :disabled="busy"><Plus :size="15"/>继续添加</button></div></header><div class="source-list"><article v-for="file in files" :key="file.path"><div class="source-copy"><strong :title="file.path">{{file.path.split(/[\\/]/).pop()}}</strong><p v-if="file.media">{{duration(file.media.duration)}} · {{file.media.width}}×{{file.media.height}} · {{codecLabel(file.media.codec)}} · {{bytes(file.media.size)}}<span v-if="file.media.hdr"> · HDR</span><span v-if="file.media.depth>8"> · {{file.media.depth}} 位</span></p><p v-if="file.error" class="error-text">{{file.error}}</p><template v-else-if="file.plan"><p class="output-name">→ {{file.plan.output_name}}</p><p v-if="o.mode==='size'">音频约 {{file.plan.audio_mb.toFixed(2)}} MB · 视频 {{Math.round(file.plan.video_kbps||0)}} kbps · 输出 {{file.plan.width}}×{{file.plan.height}}</p><p v-if="file.plan.warning" class="plan-warning">{{file.plan.warning}}</p></template></div><button class="icon-button" :disabled="busy" @click="remove(file.path)" aria-label="移除待转码文件"><X :size="16"/></button></article></div><p class="fine input-hint">可继续拖入文件。清空此列表不会取消下方已开始的任务。</p></template>
</section>
<section class="composer transcode-settings"><header class="section-heading"><strong>视频设置</strong><span>软件编码 · 保持原帧率</span></header><div class="transcode-grid">
<label>视频编码<select v-model="o.codec"><option value="h264">H.264</option><option value="h265">H.265 / HEVC</option></select></label>
<label>压制方式<select v-model="o.mode"><option value="crf">按画质 · CRF</option><option value="size">按目标大小 · 两遍编码</option></select></label>
<label v-if="o.mode==='crf'">CRF <input type="number" min="0" max="51" step="1" v-model.number="crf"><small>数值越低，通常画质越高、体积越大</small></label>
<label v-else>每个文件目标大小<div class="inline"><input class="grow" type="number" min="0.1" step="0.1" v-model.number="targetSize"><select v-model="sizeUnit" aria-label="目标大小单位"><option>MB</option><option>GB</option></select></div><small>包含音频与封装；允许少量偏差</small></label>
<label>压制预设<select v-model="preset"><option value="ultrafast">极速 · ultrafast</option><option value="veryfast">很快 · veryfast</option><option value="fast">快速 · fast</option><option value="medium">中等 · medium</option><option value="slow">慢速 · slow</option><option value="veryslow">很慢 · veryslow</option></select><small>越慢通常压缩效率越高，耗时越长</small></label>
<label>分辨率<select v-model="o.resolution"><option value="source">保持原分辨率</option><option value="custom">自定义分辨率</option></select></label>
<label>色彩与色深<select v-model="o.color"><option value="auto">自动检测 · HDR / 高色深需确认</option><option value="preserve">保留色深与 HDR（高色深需 H.265）</option><option value="sdr">转换为 SDR 8 位</option></select></label>
</div>
<div v-if="o.resolution==='custom'" class="resolution-row"><label>宽度<input type="number" min="2" max="16384" v-model.number="o.width" @change="dimensions('width')"></label><span>×</span><label>高度<input type="number" min="2" max="16384" v-model.number="o.height" @change="dimensions('height')"></label><label class="check"><input type="checkbox" v-model="o.lock_ratio" @change="dimensions(o.anchor)">锁定宽高比</label><label v-if="!o.lock_ratio">画面适配<select v-model="o.fit"><option value="pad">等比缩放并补边</option><option value="crop">裁剪填满</option><option value="stretch">拉伸（会变形）</option></select></label></div><p v-if="o.resolution==='custom'" class="fine">尺寸自动对齐为偶数。锁定时按最后修改的宽或高，依各视频的比例计算；最终尺寸见文件预览。</p>
<header class="section-heading"><strong>音频设置</strong><span>输出仅包含第一条音轨</span></header><div class="transcode-grid audio-grid"><label>音频处理<select v-model="o.audio"><option value="encode">压制音频 · AAC</option><option value="copy">复制音频流 · 不重新编码</option><option value="none">无音频流</option></select></label><label v-if="o.audio==='encode'">音频码率<select v-model="audioRate"><option :value="0">参考源音频码率</option><option v-for="n in [96,128,160,192,256,320]" :value="n">{{n}} kbps</option><option value="custom">自定义</option></select></label><label v-if="o.audio==='encode'&&customAudio">自定义 kbps<input type="number" min="16" max="512" v-model.number="o.audio_kbps"></label></div><p v-if="o.audio==='encode'&&o.audio_kbps===0" class="fine">参考源音频码率仍会重新编码；需要保留原音频请选“复制音频流”。</p>
<header class="section-heading"><strong>输出设置</strong><span>同名自动编号，避免覆盖</span></header><div class="transcode-grid"><label>封装格式<select v-model="o.container"><option value="mp4">MP4</option><option value="mkv">MKV</option><option value="mov">MOV</option></select></label><label>文件名后缀<select v-model="o.suffix_mode"><option value="auto">根据编码与压制方式自动生成</option><option value="custom">手动输入</option><option value="none">不添加</option></select></label><label v-if="o.suffix_mode==='custom'">自定义后缀<input v-model="o.suffix" placeholder="例如：剪辑版"></label><label>输出目录<select v-model="customDir"><option :value="false">保存在原文件旁边</option><option :value="true">保存到指定目录</option></select></label></div><button v-if="customDir" class="button quiet path" @click="chooseDirectory(true).catch(showError)">{{settings.batch_output_dir||'选择目录'}}</button>
<footer class="transcode-actions"><label class="check"><input type="checkbox" v-model="settings.keep_source">保留源文件</label><button class="button quiet" @click="saveSettings().catch(showError)">保存为默认设置</button><button class="button primary push-right" :disabled="!ready" @click="start"><LoaderCircle v-if="preparing||busy" :size="16" class="spin"/>{{preparing?'正在检测输出设置':`开始转码${files.length?`（${files.length}）`:''}`}}</button></footer><div class="output-plan">{{summary}}</div></section>
</template>
<style scoped>.transcode-input{border:1px dashed #cfc8ee;border-radius:10px;margin-bottom:18px;overflow:hidden}.transcode-input .drop-zone{border:0;margin:0}.input-toolbar{display:flex;align-items:center;justify-content:space-between;padding:12px 16px;border-bottom:1px solid #e8e5f2}.source-list{max-height:300px;overflow:auto}.source-list article{display:flex;align-items:flex-start;gap:16px;padding:12px 16px;border-bottom:1px solid #eeeaf6}.source-copy{min-width:0;flex:1}.source-copy strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.source-copy p{margin:4px 0;font-size:12px;overflow-wrap:anywhere}.output-name{color:#6554bf}.plan-warning{color:#93671b}.input-hint{padding:0 16px}.section-heading{display:flex;justify-content:space-between;gap:12px;margin:6px 0 14px}.section-heading:not(:first-child){border-top:1px solid #e6e7ee;padding-top:20px;margin-top:20px}.section-heading span{font-size:12px;color:#8390a5}.transcode-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.transcode-grid label,.resolution-row>label:not(.check){display:flex;flex-direction:column;gap:7px;color:#68758c;font-size:12px}.transcode-grid select,.transcode-grid input{width:100%;min-width:0}.transcode-grid .inline select{width:75px}.transcode-grid small{color:#9099ac;line-height:1.5}.resolution-row{display:flex;gap:14px;align-items:center;margin-top:16px;flex-wrap:wrap}.resolution-row input[type=number]{width:120px}.transcode-actions{display:flex;align-items:center;gap:15px;margin:20px 0 14px}.check{display:inline-flex;align-items:center;gap:8px}.check input{margin:0;flex-shrink:0}@media(max-width:1000px){.transcode-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.section-heading span{max-width:55%;text-align:right}}
</style>
