import assert from 'node:assert/strict';
import {orderedVideos,audioFor,canMp4,hasAudio,audioLabel} from '../src/formats.ts';
const f=(id,vc,ac,h,fps=24)=>({format_id:id,vcodec:vc,acodec:ac,height:h,fps,ext:vc==='none'?'m4a':'mp4',tbr:1000,abr:128});
const formats=[f('625','vp09.00.50.08','none',2160,60),f('401','av01.0.12M.08','none',2160),f('251','none','opus',0),f('140','none','mp4a.40.2',0)];
const selected=orderedVideos(formats)[0];
assert.equal(selected.format_id,'401');
assert.equal(audioFor(formats,selected).format_id,'140');
assert.equal(canMp4(selected,audioFor(formats,selected)),true);
assert.equal(canMp4(formats[0],formats[2]),false);
assert.equal(canMp4(selected,formats[2]),false);
assert.equal(canMp4(selected,undefined),true);
assert.equal(orderedVideos([formats[0],{...selected,height:1080},formats[3]])[0].format_id,'625');
assert.equal(orderedVideos(formats).find(f=>f.height<=1080),undefined);
console.log('Format selection tests passed');
import {codecLabel,sizeLabel} from '../src/formats.ts';
assert.equal(codecLabel('vp09.00.50.08'),'VP9');
assert.equal(codecLabel('av01.0.12M.08'),'AV1');
assert.equal(codecLabel('mp4a.40.2'),'AAC');
assert.equal(codecLabel('hvc1.1.6.L120.90'),'H.265');
assert.equal(sizeLabel({...formats[0],filesize_approx:104857600}),'约 100.0 MB');
assert.equal(sizeLabel({...formats[0],filesize:1048576}),'1.0 MB');
assert.equal(sizeLabel(formats[0]),'大小未知');
console.log('Simple labels and file sizes passed');
import {groupFormats} from '../src/formats.ts';
const grouped=groupFormats([...formats, {...formats[1],format_id:'av1720',height:720}], 'video');
assert.deepEqual(grouped.map(g=>g.codec),['AV1','VP9','未知']);
assert.deepEqual(grouped[0].formats.map(f=>f.height),[2160,720]);
const groupedAudio=groupFormats([formats[2],formats[3],{...formats[3],format_id:'aaclow',abr:48}], 'audio');
assert.deepEqual(groupedAudio.map(g=>g.codec),['AAC','Opus']);
assert.deepEqual(groupedAudio[0].formats.map(f=>f.abr),[128,48]);
assert.equal(orderedVideos(formats)[0].format_id,'401');
console.log('Codec grouping preserves default selection');
const unknownAudio={...f('hls-audio-English','none',null,0),ext:'mp4',abr:null};
assert.equal(hasAudio(unknownAudio),true);
assert.equal(hasAudio({...unknownAudio,acodec:'none'}),false);
assert.equal(hasAudio({...unknownAudio,vcodec:null}),false);
assert.equal(audioFor([selected,unknownAudio],selected).format_id,'hls-audio-English');
assert.equal(canMp4(selected,unknownAudio),false);
console.log('Vimeo audio-only rendition with unknown codec remains selectable');

assert.equal(audioLabel({ ...unknownAudio, abr:null }), '音轨 · 参数暂未获取');
assert.equal(audioLabel({ ...unknownAudio, acodec:'aac', abr:128, filesize_approx:320000 }), 'AAC · 约 128 kbps · 约 0.3 MB');
