use crate::*;
use std::time::Duration;

pub fn tool_root(app:&AppHandle)->PathBuf{app_data_dir(app).join("tools")}
pub fn managed_path(app:&AppHandle,tool:&str)->Option<PathBuf>{let root=tool_root(app);let data:Value=serde_json::from_slice(&fs::read(root.join("active.json")).ok()?).ok()?;let key=if tool=="ffprobe"{"ffmpeg"}else{tool};let dir=data.get(key)?.get("directory")?.as_str()?;if dir.contains(['/', '\\'])||dir=="."||dir==".."{return None}let path=root.join(dir).join(format!("{tool}.exe"));path.is_file().then_some(path)}
fn initialize(app:&AppHandle)->Result<(),String>{let root=tool_root(app);fs::create_dir_all(&root).map_err(|e|e.to_string())?;if !root.join("active.json").is_file(){let manifest=resource_path(app,"bin/bundled-tools.json");let mut json:Value=serde_json::from_slice(&fs::read(manifest).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;let dir=root.join("bundled-0.2.0");fs::create_dir_all(&dir).map_err(|e|e.to_string())?;for exe in ["yt-dlp.exe","ffmpeg.exe","ffprobe.exe","deno.exe"]{fs::copy(resource_path(app,&format!("bin/{exe}")),dir.join(exe)).map_err(|e|e.to_string())?;}if let Some(items)=json.as_object_mut(){for value in items.values_mut(){value["directory"]="bundled-0.2.0".into()}}atomic_json(&root.join("active.json"),&json)?;}Ok(())}
pub fn resource_path(app:&AppHandle,relative:&str)->PathBuf{if let Ok(dir)=app.path().resource_dir(){let p=dir.join(relative);if p.is_file(){return p}}PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("resources").join(relative)}
#[tauri::command]pub async fn manage_tools(app:AppHandle,action:String,only:String)->Result<Value,String>{tauri::async_runtime::spawn_blocking(move||manage(&app,&action,&only)).await.map_err(|e|e.to_string())?}
pub fn manage(app:&AppHandle,action:&str,only:&str)->Result<Value,String>{if !matches!(action,"check"|"update"|"rollback"){return Err("无效更新操作".into())}if !matches!(only,"all"|"yt-dlp"|"ffmpeg"|"deno"){return Err("无效工具".into())}let q=app.state::<queue::Queue>();let _guard=q.tools.try_write().map_err(|_|"工具正在使用，请等待解析、下载或转码完成")?;if !q.running.lock().unwrap().is_empty(){return Err("请在任务结束后更新工具".into())}initialize(app)?;let root=tool_root(app);if action=="rollback"{let previous:Value=serde_json::from_slice(&fs::read(root.join("previous.json")).map_err(|_|"没有可恢复的上一版本")?).map_err(|e|e.to_string())?;for tool in ["yt-dlp","ffmpeg","deno"]{let dir=previous[tool]["directory"].as_str().ok_or("无效恢复记录")?;if dir.contains(['/', '\\'])||dir==".."{return Err("无效恢复路径".into())}let exe=root.join(dir).join(format!("{tool}.exe"));let arg=if tool=="ffmpeg"{"-version"}else{"--version"};process::run(&exe,vec![arg.into()],Duration::from_secs(20),|_|{})?;}let current:Value=serde_json::from_slice(&fs::read(root.join("active.json")).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;atomic_json(&root.join("active.json"),&previous)?;atomic_json(&root.join("previous.json"),&current)?;return Ok(serde_json::json!({"restored":true}))}
let settings=q.data.lock().unwrap().settings.clone();let mut args=vec!["-NoProfile".into(),"-NonInteractive".into(),"-ExecutionPolicy".into(),"Bypass".into(),"-File".into(),resource_path(app,"fetch-tools.ps1").into_os_string(),"-Destination".into(),root.into_os_string(),"-Only".into(),only.into()];if settings.use_proxy&&!settings.proxy.trim().is_empty(){args.extend(["-Proxy".into(),settings.proxy.into()]);}if action=="check"{args.push("-CheckOnly".into())}let _=app.emit("tools-status","正在连接发布源并校验工具");let result=process::run(Path::new("powershell.exe"),args,Duration::from_secs(1800),|_|{})?;let value=serde_json::from_str(result.stdout.trim()).map_err(|e|format!("更新结果解析失败：{e}\n{}",result.stdout))?;let _=app.emit("tools-status","工具检查完成");Ok(value)}
pub fn start_auto(app:&AppHandle){let app=app.clone();thread::spawn(move||{thread::sleep(Duration::from_secs(12));for _ in 0..120 {if !app.state::<queue::Queue>().data.lock().unwrap().settings.auto_update{return}match manage(&app,"update","all"){Ok(_)=>{let _=app.emit("tools-status","自动更新检查完成");return},Err(e) if e.contains("正在使用")||e.contains("任务结束")=>thread::sleep(Duration::from_secs(30)),Err(e)=>{let _=app.emit("tools-status",format!("自动更新未完成：{e}"));return}}}});}
